//
//  StyleKitName.cs
//  ProjectName
//
//  Created by Frank Caico on 11/16/14.
//  Copyright (c) 2014 YuFit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



using System;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.CoreGraphics;

namespace ProjectName
{
    [Register ("StyleKitName")]
    public class StyleKitName : NSObject
    {

        //// Initialization

        static StyleKitName()
        {
        }

        //// Drawing Methods

        public static void DrawArrowSlider(UIColor fillColor, UIColor outlineColor, float percentFull, PointF position, SizeF overallSize)
        {
            //// General Declarations
            var context = UIGraphics.GetCurrentContext();


            //// Variable Declarations
            var sizeOfFill = percentFull * overallSize.Width < 35.0f ? new SizeF(35.0f, overallSize.Height) : new SizeF(percentFull * overallSize.Width, overallSize.Height);

            //// Outline Drawing
            RectangleF outlineRect = new RectangleF(position.X, position.Y, overallSize.Width, overallSize.Height);
            context.SaveState();
            context.ClipToRect(outlineRect);
            context.Translate(context, outlineRect.X, outlineRect.Y);

            StyleKitName.DrawArrowOutline(new RectangleF(0.0f, 0.0f, outlineRect.Width, outlineRect.Height), outlineColor);
            context.RestoreState();


            //// Fill Drawing
            RectangleF fillRect = new RectangleF(position.X, position.Y, sizeOfFill.Width, sizeOfFill.Height);
            context.SaveState();
            context.ClipToRect(fillRect);
            context.Translate(context, fillRect.X, fillRect.Y);

            StyleKitName.DrawArrowFill(new RectangleF(0.0f, 0.0f, fillRect.Width, fillRect.Height), fillColor);
            context.RestoreState();
        }

    }
}
